SLACK_CHANNEL_NAME=build-status
ENVIRONMENT=prod
CODE_BASE_PATH=/var/lib/jenkins/workspace/ansible-monitoring
ACTION_MESSAGE=Grafana and Prometheus deployment completed
KEEP_APPROVAL_STAGE=true
ANSIBLE_REPO_URL=https://github.com/iamsahil252/Ansible-Assignment-5.git
ANSIBLE_BRANCH=main
